# 基础3DGS配置
model:
  sh_degree: 3
  source_path: "data/"
  model_path: "output/"
  resolution: -1
  white_background: False
  data_device: "cuda"
  eval: True

optimization:
  iterations: 30000
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001
  
  # 密度化参数
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002
